import { ms, px, rem, type TokenTree } from "./token-helpers";

export const designTokens = {
  fontFamily: {
    sans: '"Noto Sans", "Segoe UI", Helvetica, Arial, sans-serif',
    serif: '"IBM Plex Serif", Georgia, "Times New Roman", serif',
    mono: '"IBM Plex Mono", "SFMono-Regular", Menlo, monospace',
  },
  font: {
    family: "var(--font-family-sans)",
  },
  fontSize: {
    xs: rem(0.75),
    sm: rem(0.875),
    base: rem(1),
    lg: rem(1.125),
    xl: rem(1.25),
    "2xl": rem(1.5),
    "3xl": rem(1.875),
    "4xl": rem(2.25),
  },
  lineHeight: {
    tight: 1.2,
    snug: 1.35,
    normal: 1.5,
    relaxed: 1.65,
    loose: 1.8,
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  letterSpacing: {
    tighter: "-0.02em",
    tight: "-0.01em",
    normal: "0em",
    wide: "0.01em",
    wider: "0.02em",
  },
  typography: {
    bodySmall: {
      size: "var(--font-size-sm)",
      lineHeight: "var(--line-height-normal)",
      weight: "var(--font-weight-regular)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
    body: {
      size: "var(--font-size-base)",
      lineHeight: "var(--line-height-relaxed)",
      weight: "var(--font-weight-regular)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
    bodyLarge: {
      size: "var(--font-size-lg)",
      lineHeight: "var(--line-height-relaxed)",
      weight: "var(--font-weight-regular)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
    subtitle: {
      size: "var(--font-size-sm)",
      lineHeight: "var(--line-height-snug)",
      weight: "var(--font-weight-medium)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
    title: {
      size: "var(--font-size-lg)",
      lineHeight: "var(--line-height-tight)",
      weight: "var(--font-weight-semibold)",
      letterSpacing: "var(--letter-spacing-tight)",
    },
    titleLarge: {
      size: "var(--font-size-2xl)",
      lineHeight: "var(--line-height-tight)",
      weight: "var(--font-weight-semibold)",
      letterSpacing: "var(--letter-spacing-tight)",
    },
    caption: {
      size: "var(--font-size-xs)",
      lineHeight: "var(--line-height-normal)",
      weight: "var(--font-weight-regular)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
    label: {
      size: "var(--font-size-sm)",
      lineHeight: "var(--line-height-tight)",
      weight: "var(--font-weight-medium)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
    overline: {
      size: "var(--font-size-xs)",
      lineHeight: "var(--line-height-normal)",
      weight: "var(--font-weight-semibold)",
      letterSpacing: "var(--letter-spacing-wide)",
    },
    code: {
      family: "var(--font-family-mono)",
      size: "var(--font-size-sm)",
      lineHeight: "var(--line-height-normal)",
      weight: "var(--font-weight-regular)",
      letterSpacing: "var(--letter-spacing-normal)",
    },
  },
  motion: {
    duration: {
      instant: ms(0),
      fast: ms(120),
      normal: ms(200),
      slow: ms(320),
      slower: ms(480),
    },
    ease: {
      standard: "cubic-bezier(0.2, 0, 0, 1)",
      emphasized: "cubic-bezier(0.2, 0, 0, 1.2)",
      decelerate: "cubic-bezier(0, 0, 0, 1)",
      accelerate: "cubic-bezier(0.4, 0, 1, 1)",
      linear: "linear",
    },
  },
  radius: {
    xs: rem(0.125),
    sm: rem(0.25),
    md: rem(0.5),
    lg: rem(0.75),
    xl: rem(1),
    "2xl": rem(1.5),
    "3xl": rem(2),
    "4xl": rem(2.5),
    "5xl": rem(3),
    full: "9999px",
  },
  shadow: {
    xs: "0 1px 2px 0 rgb(0 0 0 / 0.06)",
    sm: "0 2px 4px 0 rgb(0 0 0 / 0.08)",
    md: "0 6px 12px -4px rgb(0 0 0 / 0.12)",
    lg: "0 12px 24px -8px rgb(0 0 0 / 0.18)",
    xl: "0 16px 32px -12px rgb(0 0 0 / 0.24)",
    "2xl": "0 24px 48px -16px rgb(0 0 0 / 0.28)",
    none: "0 0 #0000",
  },
  z: {
    base: 0,
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    overlay: 1040,
    modal: 1050,
    popover: 1060,
    toast: 1080,
    tooltip: 1090,
    max: 2147483647,
  },
  backdropBlur: {
    none: rem(0),
    xs: px(2),
    sm: px(4),
    md: px(8),
    lg: px(12),
    xl: px(16),
    "2xl": px(24),
    "3xl": px(40),
  },
  spacing: {
    none: rem(0),
    "2xs": rem(0.125),
    xs: rem(0.25),
    sm: rem(0.5),
    md: rem(0.75),
    lg: rem(1),
    xl: rem(1.5),
    "2xl": rem(2),
    "3xl": rem(3),
    "4xl": rem(4),
    "5xl": rem(6),
  },
} as const satisfies TokenTree;

export type DesignTokens = typeof designTokens;
