export const mockFeeds = [
  {
    id: "feed-1",
    title: "The Future of Web Development: What's Next After React?",
    description:
      "Exploring emerging frameworks and technologies that might replace or complement React in the coming years.",
    source: "TechCrunch",
    date: "2 hours ago",
    type: "article",
    image: "/placeholder.svg?height=400&width=600",
    url: "https://example.com/article1",
    favorite: true,
  },
  {
    id: "feed-2",
    title: "10 Essential Productivity Tools for Remote Workers",
    description: "A curated list of the best tools to boost your productivity while working from home.",
    source: "ProductivityWeekly",
    date: "Yesterday",
    type: "article",
    image: "/placeholder.svg?height=400&width=600",
    url: "https://example.com/article2",
    favorite: false,
  },
  {
    id: "feed-3",
    title: "The Science of Sleep: How to Optimize Your Rest",
    description: "New research reveals the best practices for getting quality sleep and improving your overall health.",
    source: "HealthInsider",
    date: "2 days ago",
    type: "article",
    image: "/placeholder.svg?height=400&width=600",
    url: "https://example.com/article3",
    favorite: false,
  },
  {
    id: "feed-4",
    title: "Tech Talk: The Rise of AI in Everyday Applications",
    description:
      "In this episode, we discuss how artificial intelligence is becoming integrated into the tools we use daily.",
    source: "TechPodcast",
    date: "3 days ago",
    type: "podcast",
    image: "/placeholder.svg?height=400&width=400",
    url: "https://example.com/podcast1",
    audioUrl: "https://example.com/podcast1.mp3",
    duration: "45 min",
    favorite: true,
  },
  {
    id: "feed-5",
    title: "Minimalist Design Principles for Modern Websites",
    description:
      "Learn how to apply minimalist design principles to create clean, effective, and user-friendly websites.",
    source: "DesignDaily",
    date: "4 days ago",
    type: "article",
    image: "/placeholder.svg?height=400&width=600",
    url: "https://example.com/article4",
    favorite: false,
  },
  {
    id: "feed-6",
    title: "The History of Programming Languages",
    description:
      "A deep dive into how programming languages evolved from machine code to the high-level languages we use today.",
    source: "CodeStory",
    date: "5 days ago",
    type: "podcast",
    image: "/placeholder.svg?height=400&width=400",
    url: "https://example.com/podcast2",
    audioUrl: "https://example.com/podcast2.mp3",
    duration: "60 min",
    favorite: false,
  },
  {
    id: "feed-7",
    title: "Sustainable Tech: Reducing Your Digital Carbon Footprint",
    description:
      "Practical tips for making your digital life more environmentally friendly without sacrificing productivity.",
    source: "GreenTech",
    date: "1 week ago",
    type: "article",
    image: "/placeholder.svg?height=400&width=600",
    url: "https://example.com/article5",
    favorite: true,
  },
  {
    id: "feed-8",
    title: "Financial Independence: Investing for Beginners",
    description:
      "Start your investment journey with these fundamental principles and strategies for long-term wealth building.",
    source: "MoneyMatters",
    date: "1 week ago",
    type: "article",
    image: "/placeholder.svg?height=400&width=600",
    url: "https://example.com/article6",
    favorite: false,
  },
  {
    id: "feed-9",
    title: "Entrepreneurship Uncovered: Startup Success Stories",
    description: "Interviews with founders who built successful companies and the lessons they learned along the way.",
    source: "StartupDaily",
    date: "2 weeks ago",
    type: "podcast",
    image: "/placeholder.svg?height=400&width=400",
    url: "https://example.com/podcast3",
    audioUrl: "https://example.com/podcast3.mp3",
    duration: "55 min",
    favorite: false,
  },
]

